### ISSUE TITLE
Continue receving headers

### ISSUE THREAD

**Issue by drSaesh** [napengam/phpWebSocketServer#1]
Hello,

there is some trouble sometimes in the handshake process especially in completion the header.
I cant reproduce the cause of it but sometimes the phpWebSocketServer is going into deadloop.

I run the phpWebSocketServer on a linux system. I tried out bufferLength 2048 and 10 * 4096 with the same trouble.

Do you have any idea what can i do to fix that problem?

**Comment by napengam** [comment]
In webSocketServer.php just delete or comment these  lines  112 up to 115
            
if (strpos(str_replace("\r", '', $dataBuffer), "\n\n") === false){   
      $this->onOther($SocketID, "Continue receving headers");  
           continue;  
 }
