### ISSUE TITLE
code improvements

### ISSUE THREAD

**Issue by nikto1** [napengam/phpWebSocketServer#2]
Looking at the code you could do some improvements:
e.g.: 
1) in the php file RFC_6455.php the function "extractIPort" could be solved with a simple preg_split() pattern like "/:(?=[0-9]+$)/" or similar, no need for the loop.
2) On line 406  in the file "webSocketServer.php" you should probably "`return false;`" instead of "`$ok = false;`". Also the` $ok = true; $ok = false;` stuff doesn't make much sense inside the "specificChecks" function.
3) always declare public, protected or private before a function.
4) you're mixing up uppercase/ lowercase letters in variables, functions, which makes the code confused. On line 327 you've written "`$this->onCLose`", which should be "`$this->onClose`" i think.
5) On your website in the last paragraph "be careful" you stated that using websockets is not without risk, but this is also the case with forms: Just do the appropriate checks on server side and you're good.

Good work anyway.
Regards

**Comment by napengam** [comment]
I am late sorry ...
Thanks for your input, I will change accordingly if possible.
Regards
Heinz
