### ISSUE TITLE
Bug in phpWebSocketServer/phpClient /websocketCore.php

### ISSUE THREAD

**Issue by juedan** [napengam/phpWebSocketServer#4]
Hello.

First thanks for the modules to handle WebSockets. This brings my project (informing users about severe weather warnings and renewing weather warning maps) a great step forward.

In the module phpWebSocketServer/phpClient/**websocketCore.php** there is a bug in line 166:
`$req[] = "Client-Type: php";  // hgs private , not part of RCF7455`
but I think this should be
`$req[] = "Client-Type: " . $app;  // hgs private , not part of RCF7455`

Best regards

Juergen

PS: Here is the link to the line:
https://github.com/napengam/phpWebSocketServer/blob/519e354f9bcf2f968df4a436dce85eeb48e6c74d/phpClient/websocketCore.php#L166

**Comment by napengam** [comment]
It has to be hardcoded 'php' to tell server about type of client, not about type of $app.
This is because the server responds different to clients of type 'php' then to clients of type 'websocket' 
that will typicaly be JavaScript/Web clients.
